declare namespace NodeJS {
  interface ProcessEnv {
    PORTFOLIO_CLIENT_BREAKPOINT_MD: number;
    PORTFOLIO_CLIENT_BREAKPOINT_LG: number;
    PORTFOLIO_CLIENT_BREAKPOINT_XL: number;
    PORTFOLIO_CLIENT_BREAKPOINT_XXL: number;
    PORTFOLIO_CLIENT_BREAKPOINT_2K: number;
    PORTFOLIO_CLIENT_BREAKPOINT_4K: number;
    PORTFOLIO_CLIENT_BREAKPOINT_LANDSCAPE: number;
    PORTFOLIO_CLIENT_BREAKPOINT_SMALL_SCREEN: number;
  }
}
